[tasks.live-build]
watch = { ignore_pattern = "docs/*"}
command = "wasm-pack"
args = ["build", "--debug", "-t", "web", "-d", "docs", "--no-typescript"]
dependencies = ["check", "migrate-index"]

[tasks.build-release]
command = "wasm-pack"
args = ["build", "--release", "-t", "web", "-d", "docs", "--no-typescript"]

[tasks.cleanup]
command = "rm"
args= ["docs/.gitignore", "docs/package.json"]

[tasks.cleanbuild]
command = "rm"
args = ["-rf", "docs"]

[tasks.migrate-index]
command = "cp"
args = ["-f", "static/index.html", "docs/"]

[tasks.make-release]
dependencies = ["cleanbuild", "build-release", "cleanup", "migrate-index", "gzip"]

[tasks.gzip]
command = "gzip"
args = ["-rk9f", "docs/"]


[tasks.check]
command = "cargo"
args = ["check"]
